### ISSUE TITLE
Spike - UDPIngress API completeness

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#1079]
The purpose of this issue is to spike and then track the requirements to graduate `UDPIngress` into a GA API.

This relates to https://github.com/Kong/kubernetes-ingress-controller/pull/1057 wherein we provided an initial POC of `UDPIngress` with `v1alpha1`.

The requirements are:

- [x] ~design service backend functionality~ (to be implemented in https://github.com/Kong/kubernetes-ingress-controller/issues/1080)
- [x] ~unit tests for all relevant `UDPIngress` functionality added to 100% coverage~ (to be implemented in https://github.com/Kong/kubernetes-ingress-controller/issues/1080)
- [x] ~integration test coverage for `UDPIngress` to reduce the risk of later regressions~ (to be implemented in https://github.com/Kong/kubernetes-ingress-controller/issues/1080)
- [x] ~documentation for the API provided, including basic usage, examples, and guides~ (to be implemented in https://github.com/Kong/kubernetes-ingress-controller/issues/1080)

Resolving this issue should be a result of spiking the issue and creating the relevant follow-up issues.

**Comment by mflendrich** [comment]
@shaneutt is to propose a way forward for whether 2.0 will come with UDPIngress v1alpha1 or v1beta1, and to refine issues https://github.com/Kong/kubernetes-ingress-controller/issues/1080 and https://github.com/Kong/kubernetes-ingress-controller/issues/1081 according to the results of the spike.

**Comment by shaneutt** [comment]
https://github.com/Kong/kubernetes-ingress-controller/issues/1080 is the relevant follow up item and is the required work to get us to GA.
