### ISSUE TITLE
Move the release checklist from a markdown to an issue template

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#1647]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Fact: Today our release checklist lives in a markdown file in the repo.
Observation: it feels challenging to schedule releases, and track completion of all work items that make a release complete.
Observation: maintainers sometimes miss scheduled releases because performing them is not tracked on our board

### Proposed Solution

- Create an issue template "Release/Pre-release"
- Move the release checklist from the markdown file in the repo to the acceptance criteria of the release issue template, and make them checkboxes
- Going forward, schedule releases as tasks in the backlog/on the board

### Acceptance Criteria

- [ ] Release issue template exists in the KIC repo
- [ ] Release issue template contains a default set of acceptance criteria - a list of checkboxes, each corresponding to a step of the release checklist
- [ ] Release issue template works both for releases and for pre-releases (adjustment of the checklist may be necessary)
- [ ] Release issue template sets a distinguishing label, e.g. `release`, on the issues.

**Comment by shaneutt** [comment]
I think we can scope this down to simply creating an issue template to consider this one resolved. I think we can just manually create those issues for now as needed when we intend to release to keep it simple.

**Comment by mflendrich** [comment]
> I think we can scope this down to simply creating an issue template to consider this one resolved.

I may be understanding the current ACs in a different way than you are, but these all are intended to describe certain specific features of that issue template. I'm rewording them to make it clearer.

Please suggest a specific subset of ACs if you think we should scope it down.

**Comment by shaneutt** [comment]
I think the part I was confused on was `Going forward, schedule releases as tasks in the backlog/on the board`. I took that as some kind of extra organizational or automation bit but if that's not the case then no worries my misunderstanding :+1:
