### ISSUE TITLE
Gateway APIs Milestone 1 - Gateway Controller

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#1945]
### Feature

The purpose of this issue is to implement `Gateway` from [Gateway API](https://github.com/kubernetes-sigs/gateway-api) at a basic level that supports what we will call "existing gateway mode". That is to say: we wont have any provisioning or lifecycle management of the Gateway for this milestone, but instead will have logic that will enable linking a `Gateway` resource to an existing, already deployed Kong Gateway.

### Proposed Solution

- [x] introduce our official `GatewayClassName` that will be used to identify Kong managed `Gateway` resources from here on out
- [x] implement a controller for `Gateway` which resolves resources via "existing gateway mode" and populates the Gateway spec/status according to the `--publish-service` controller manager flag
- [x] add a `GatewayAPI` feature gate to enable the controller
- [x] add integration tests which cover all supported features

### Prerequisites

- [x] https://github.com/Kong/kubernetes-ingress-controller/pull/1970

### Acceptance Criteria

- [x] a combination of `GatewayClass` and `Gateway` resource can be posted which will resolve to an existing Kong Gateway already in the cluster, and populate the spec/status accordingly
