### ISSUE TITLE
Gateway APIs Milestone 1  - HTTPRoute Controller

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#1947]
### Feature

The purpose of this issue is to implement support for `HTTPRoute` from [Gateway API](https://github.com/kubernetes-sigs/gateway-api) for HTTP ingress traffic.

### Proposed Solution

- [x] add `examples/` which includes a full and working `GatewayClass`, `Gateway`, `HTTPRoute` example
- [x] add an `HTTPRoute` controller with predicates and logic to handle `Gateway` parentRefs
`Spec.ControllerName` changed to something unsupported
- [x] add poc level HTTPRoute translation support for the data-plane
- [x] add integration tests

### Prerequisites

- [x] https://github.com/Kong/kubernetes-ingress-controller/issues/1945
