### ISSUE TITLE
Gateway APIs Cleanup - RBAC, Logging, docs, examples

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#1988]
The purpose of this issue is to be a cleanup reminder that the following things need to be accounted for after all other components of milestone 1 are completed:

- [x] adequate log entries have been added to all controllers
- [x] some debug log entries need to be reviewed and potentially promoted to info level
- [x] documentation for Gateway APIs exists for early adopters
- [x] RBAC permissions for Gateway APIs are fixed (previously created with wrong group)
- [x] working `examples/` for GatewayAPIs are created
