### ISSUE TITLE
HTTPRoute: Data-Plane Translation

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#2079]
### Problem Statement

https://github.com/Kong/kubernetes-ingress-controller/pull/2081 provided a controller and a starting point for basic parser translate logic for `HTTPRoutes`. The purpose of this task is to finish full spec support for `HTTPRoute`.

### Acceptance

- [x] as a user I can use the `HTTPRoute` API specification with KIC
- [x] if a feature of `HTTPRoute` is not supported by KIC, I find out quick and upfront via API validation and not via logs later
- [x] parser logic for HTTPRoute implemented and covering the basic route matching portion of the spec
- [x] webhook validation for `HTTPRoute` blocking all unimplemented features
- [x] code refactoring and cleanup
- [x] unit tests for refactored parser functions
