### ISSUE TITLE
Gateway API compliance path

### ISSUE THREAD

**Issue by mlavacca** [Kong/kubernetes-ingress-controller#2849]
### Problem statement

KIC has been updated and now all the upstream core conformance tests are passing (https://github.com/kubernetes-sigs/gateway-api/tree/main/conformance/tests). Nonetheless, compliance with the Gateway API conformance tests does not automatically imply full compliance with the Gateway API itself. This happens because the Gateway API conformance test suite is not complete yet, and some tests may have flaws or the suite may not test some core functionalities.

This issue's goal is to keep track of our Gateway API compliance debt discovered so far.

### Acceptance Criteria

- [x] gateway tests expecting the wrong ListenerConditionReason: https://github.com/kubernetes-sigs/gateway-api/issues/1297. Fixed by #3024.
- [x]  set  the listener `ResolvedRefs` status condition as failed with reason `InvalidCertificateRef` when a nonexistent TLS secret is referenced: https://github.com/kubernetes-sigs/gateway-api/issues/1318.  Fixed by #3024.
- [x]  set the listener `ResolvedRefs` status condition as failed with reason `ListenerReasonInvalidRouteKinds` when a listener supports a Route type incompatible with the `ProtocolType`: https://github.com/kubernetes-sigs/gateway-api/pull/1320.  Fixed by #3024.
- [x]  Always enforce `ResolvedRefs` condition in `HTTPRoute` and `Gateway`, not only when they are failing
- [x]  Convert the core filter RequestRedirect to the proper Kong plugin: https://github.com/Kong/kubernetes-ingress-controller/issues/2848. Fixed by #3702

**Comment by mflendrich** [comment]
@mlavacca could you please update the scope & AC to match what is left to be done? Looks like much of this is already completed.

**Comment by mlavacca** [comment]
closing as completed
