### ISSUE TITLE
Visibility of Gateway API documentation to be on par with Ingress

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#2878]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

A limiting factor for GW API adoption is the limited visibility of Gateway API documentation.
Our guides, references etc. are focused on Ingress; GW API is located in very specific GW API articles.

### Proposed Solution

On the high level: Present GW API alongside Ingress.

### Acceptance Criteria

- [ ] As a KIC user, I would like the KIC Gateway API documentation to be easily accessible, so I can learn how to leverage Gateway API, an upcoming k8s standard, together with KIC.
  - [x] The documentation correctly states that Gateway API status in current KIC release. The banner, that indicated an alpha maturity is gone.
  - [x]  [The Kubernetes Ingress Controller Design](https://docs.konghq.com/kubernetes-ingress-controller/latest/concepts/design/) mention the Gateway API.
  - [x] [The deployment section](https://docs.konghq.com/kubernetes-ingress-controller/latest/deployment/overview/) describes has an article that describes how to enable Gateway API in KIC and how to deploy the CRDs. 
  - [x] [Getting started](https://docs.konghq.com/kubernetes-ingress-controller/2.6.x/guides/getting-started/), probably one of the first steps for most users, mentions the Gateway API.
  - [ ] [Other guides](https://docs.konghq.com/kubernetes-ingress-controller/latest/guides/overview/) that has Ingress examples are interwoven with Gateway API examples. Example articles to modify:
    - https://docs.konghq.com/kubernetes-ingress-controller/2.6.x/guides/using-tcpingress/
    - https://docs.konghq.com/kubernetes-ingress-controller/2.6.x/guides/using-udpingress/
    - https://docs.konghq.com/kubernetes-ingress-controller/2.6.x/guides/using-ingress-with-grpc/

### Subissues:
- https://github.com/Kong/kubernetes-ingress-controller/issues/2966
- https://github.com/Kong/kubernetes-ingress-controller/issues/2967
- https://github.com/Kong/kubernetes-ingress-controller/issues/2968
- https://github.com/Kong/kubernetes-ingress-controller/issues/2969
- https://github.com/Kong/kubernetes-ingress-controller/issues/3215

**Comment by mflendrich** [comment]
@shaneutt suggested that interweaving GW API examples with Ingress examples is the way to go.

**Comment by rainest** [comment]
We should enable the beta API flag by default or wait for the L4 route types to graduate if we want to do this. If we want to encourage adoption by presenting Gateway options first in the docs, we don't want to have some guides use Gateway APIs (HTTP configuration with HTTPRoute, which is beta) and others (UDP routing, where UDPRoute is in alpha) either not use Gateway APIs (the guide would still present UDPIngress first or only) or require toggling the flag on (the guides require you go back through some other install guide first to update your Deployment).

**Comment by jrsmroz** [comment]
Grooming notes.

Articiles that may need update 
- https://docs.konghq.com/kubernetes-ingress-controller/latest/concepts/design/

- [This article](https://docs.konghq.com/kubernetes-ingress-controller/latest/concepts/gateway-api/) and also [this](https://docs.konghq.com/kubernetes-ingress-controller/2.6.x/guides/using-gateway-api/), mentions that the GW API is `This feature is released as a [tech preview](https://docs.konghq.com/gateway/latest/availability-stages/#tech-preview) (alpha-quality) and should not be deployed in a production environment.` It discourages usage of Gateway API. AFAIK it's no longer alpha, that should be removed.

- None of the [Deployment articles](https://docs.konghq.com/kubernetes-ingress-controller/latest/deployment/overview/) describe how to enable the gateway api feature and deploy the CRDs.

- [Getting started](https://docs.konghq.com/kubernetes-ingress-controller/2.6.x/guides/getting-started/), probably one of the first steps for most users, does not mention the Gateway API at all. I believe it would be beneficial if it would.

- Could use a version of the following articiles that mentions the gateway api
  - https://docs.konghq.com/kubernetes-ingress-controller/2.6.x/guides/using-tcpingress/
  - https://docs.konghq.com/kubernetes-ingress-controller/2.6.x/guides/using-udpingress/
  - https://docs.konghq.com/kubernetes-ingress-controller/2.6.x/guides/using-ingress-with-grpc/

**Comment by jrsmroz** [comment]
> We should enable the beta API flag by default or wait for the L4 route types to graduate if we want to do this.

@rainest : Seems like waiting for L4 route would delay our effort to make KIC support for Gateway API more visible.

> If we want to encourage adoption by presenting Gateway options first in the docs, we don't want to have some guides use Gateway APIs (HTTP configuration with HTTPRoute, which is beta) and others (UDP routing, where UDPRoute is in alpha) either not use Gateway APIs (the guide would still present UDPIngress first or only) or require toggling the flag on (the guides require you go back through some other install guide first to update your Deployment).

If I understand that correctly, if we enable the beta API, the alpha like `UDPIngress` would still be disabled? That's not ideal. This story is pretty huge anyway, I think that presenting only beta resources usage is not a bad option. Personally, I consider it better than waiting for alpha resources to graduate.

**Comment by jrsmroz** [comment]
As we discussed on the internal meeting, this issue needs more grooming, but we're fine with it for now. After we're done with subissues, we're going to revisit this story. One of the thing we intend is to open the subissue for each article in docs that mention ingress to update it to demonstrate the gateway api usage too.

**Comment by rainest** [comment]
https://github.com/Kong/kubernetes-ingress-controller/issues/2969 added a link from https://docs.konghq.com/kubernetes-ingress-controller/2.7.x/guides/getting-started/ to https://docs.konghq.com/kubernetes-ingress-controller/2.7.x/guides/using-gateway-api/. It does not add GWAPI examples to https://docs.konghq.com/kubernetes-ingress-controller/2.7.x/guides/getting-started/ itself.

The two guides essentially cover the same ground, however. They both provide instructions for adding and testing a basic route. There are some minor differences:

- The Getting Started guide covers adding plugins to the routes and services. This has some overlap with the other plugin guides, though those are all framed as being for a specific plugin. There's technically no generic "using a plugin" guide, but a hypothetical one wouldn't be much different from the "using ACL and JWT plugins" guide (it could maybe skip consumers).
- The Gateway API guide covers traffic splitting, which simply doesn't exist for Ingress.
- The Gateway API guide additionally covers beta limitations.

Do we indeed want a single guide with tabbed examples for Gateway/Ingress? Do we want to separate out the content that goes beyond the basics?

**Comment by rainest** [comment]
The [deployment guides](https://docs.konghq.com/kubernetes-ingress-controller/latest/deployment/overview/) remain something of a mess, still referencing the ancient (and long irrelevant) Kong for Kubernetes/Kong for Kubernetes Enterprise/Kong for Kubernetes with Kong Enterprise distinction.

They do all link to the Getting Started guide, however, so I'd say that's a reason in favor of consolidating the Getting Started/Gateway API guides (or at least the basic example part of the latter) into a single guide and placing the CRD install step there. You will need a restart after (the controllers auto-disable without the CRDs present), but it's one location instead of 6 in case we update steps later.
