### ISSUE TITLE
Create warning Events when k8s objects translation fails

### ISSUE THREAD

**Issue by czeslavo** [Kong/kubernetes-ingress-controller#3097]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

The parser is designed so that if it detects an issue with translating a Kubernetes object (a validation error is detected), it can skip a given object in a resulting KongState. Currently, it does so for a couple of objects, examples of such validation errors are:
- [Services all use the same Kong annotations](https://github.com/Kong/kubernetes-ingress-controller/blob/2bd0b23774fa2292bcff73920d74899a11d00971/internal/dataplane/parser/ingressrules.go#L60)
- [Gateway Listeners with more than one certificateRef are not supported](https://github.com/Kong/kubernetes-ingress-controller/blob/77c5f32b8ce31395f0a0bbe23454dafff2b93bcb/internal/dataplane/parser/parser.go#L409)
- [Invalid CA certificates](https://github.com/Kong/kubernetes-ingress-controller/blob/77c5f32b8ce31395f0a0bbe23454dafff2b93bcb/internal/dataplane/parser/translate_secrets.go#L42)

In order to make the errors' details visible to the users in a more structured format than just error logs, we would like to introduce warning `KongConfigurationTranslationFailed` Events.

### Proposed Solution

Create a [corev1.Event](https://github.com/kubernetes/api/blob/0184bd884c5e3139e1bb47b0ca149f7ffbc43c9b/core/v1/types.go#L5769) with a type `Warning` and a reason `KongConfigurationTranslationFailed` when a validation error occurs. Every event should have an involved object reference, a reason (meant to be a computer-friendly slug), and a message (meant to be a human-friendly description of the reason). By specifying an involved object, we make the event visible to a user `kubectl describe`-ing the affected resource or `kubectl get`-ting all the events (potentially filtering them by the reason we introduce).

### Suggested split of code changes 
1. [x] Introduce TranslationFailure and TranslationFailuresCollector types (#3110)
2. [x] Use TranslationFailuresCollector in the Parser (#3111)
4. [ ] Adapt existing translation errors in the Parser routines to start reporting TranslationFailures (preferably one PR per kind).
    - [x] CA certificate secrets (#3114)
    - [x] [Grouped Services annotations do not match](https://github.com/Kong/kubernetes-ingress-controller/blob/2bd0b23774fa2292bcff73920d74899a11d00971/internal/dataplane/parser/ingressrules.go#L192) (#3130)
    - [x] [Missing client-cert secret](https://github.com/Kong/kubernetes-ingress-controller/blob/2bd0b23774fa2292bcff73920d74899a11d00971/internal/dataplane/parser/ingressrules.go#L86) (#3137)
    - [x] [Invalid ingress rule path](https://github.com/Kong/kubernetes-ingress-controller/blob/ac680a396301147449f764840a8365c1c62f5864/internal/dataplane/parser/translate_ingress.go#L69) (#3138)
    - [x] [Gateway Listeners with more than one certificateRef are not supported](https://github.com/Kong/kubernetes-ingress-controller/blob/7220e7b10e2aa1e242f070915d70fe61e6eaf96a/internal/dataplane/parser/parser.go#L424) (#3147)
    - [x] [Secret reference not allowed by ReferenceGrant](https://github.com/Kong/kubernetes-ingress-controller/blob/7220e7b10e2aa1e242f070915d70fe61e6eaf96a/internal/dataplane/parser/parser.go#L462) ([handled by the controller](https://github.com/Kong/kubernetes-ingress-controller/blob/ec0f2702b99f8a75581e5c789bdf57a062ad1491/internal/controllers/gateway/gateway_utils.go#L442))
    - [x] [Missing certificate secret (Gateway)](https://github.com/Kong/kubernetes-ingress-controller/blob/7220e7b10e2aa1e242f070915d70fe61e6eaf96a/internal/dataplane/parser/parser.go#L475) ([handled by the controller](https://github.com/Kong/kubernetes-ingress-controller/blob/ec0f2702b99f8a75581e5c789bdf57a062ad1491/internal/controllers/gateway/gateway_utils.go#L462))
    - [x] [Failed to construct certificate from secret (Gateway)](https://github.com/Kong/kubernetes-ingress-controller/blob/7220e7b10e2aa1e242f070915d70fe61e6eaf96a/internal/dataplane/parser/parser.go#L485) (#3147)
    - [x] [CertificateRefs to kinds other than Secret are not supported](https://github.com/Kong/kubernetes-ingress-controller/blob/7220e7b10e2aa1e242f070915d70fe61e6eaf96a/internal/dataplane/parser/parser.go#L439) ([handled by the controller](https://github.com/Kong/kubernetes-ingress-controller/blob/ec0f2702b99f8a75581e5c789bdf57a062ad1491/internal/controllers/gateway/gateway_utils.go#L450))
    - [x] [Failed to construct certificate from secret (Ingress)](https://github.com/Kong/kubernetes-ingress-controller/blob/7220e7b10e2aa1e242f070915d70fe61e6eaf96a/internal/dataplane/parser/parser.go#L531) (#3150)
    - [x] [Missing certificate secret (Ingress)](https://github.com/Kong/kubernetes-ingress-controller/blob/7220e7b10e2aa1e242f070915d70fe61e6eaf96a/internal/dataplane/parser/parser.go#L523) (#3150)
    - [x] [Invalid service target port number](https://github.com/Kong/kubernetes-ingress-controller/blob/7220e7b10e2aa1e242f070915d70fe61e6eaf96a/internal/dataplane/parser/parser.go#L702) (#3145)
    - [x] [Could not translate Ingress Path %s to Kong paths](https://github.com/Kong/kubernetes-ingress-controller/blob/ac680a396301147449f764840a8365c1c62f5864/internal/dataplane/parser/translate_ingress.go#L253) (#3138)
    - [x] [Invalid TCPIngress rule port](https://github.com/Kong/kubernetes-ingress-controller/blob/e6586b37c79213fbe7ee25a989f5a65d3684047a/internal/dataplane/parser/translate_kong_l4.go#L42) (#3136)
    - [x] [Invalid TCPIngress: empty serviceName](https://github.com/Kong/kubernetes-ingress-controller/blob/e6586b37c79213fbe7ee25a989f5a65d3684047a/internal/dataplane/parser/translate_kong_l4.go#L62) (#3136)
    - [x] [Invalid TCPIngress: invalid servicePort](https://github.com/Kong/kubernetes-ingress-controller/blob/e6586b37c79213fbe7ee25a989f5a65d3684047a/internal/dataplane/parser/translate_kong_l4.go#L66) (#3136)
    - [x] [Invalid UDPIngress: invalid port](https://github.com/Kong/kubernetes-ingress-controller/blob/e6586b37c79213fbe7ee25a989f5a65d3684047a/internal/dataplane/parser/translate_kong_l4.go#L130) (#3136)
    - [x] [Invalid UDPIngress: empty serviceName](https://github.com/Kong/kubernetes-ingress-controller/blob/e6586b37c79213fbe7ee25a989f5a65d3684047a/internal/dataplane/parser/translate_kong_l4.go#L134) (#3136)
    - [x] [Invalid UDPIngress: invalid servicePort](https://github.com/Kong/kubernetes-ingress-controller/blob/e6586b37c79213fbe7ee25a989f5a65d3684047a/internal/dataplane/parser/translate_kong_l4.go#L138) (#3136)
    - [x] [Can't find Ingress backing kubernetes service](https://github.com/Kong/kubernetes-ingress-controller/blob/6988320be0b461f09a5213634a8be8bc39b549a6/internal/dataplane/parser/parser.go#L303) (#3138)
    - [x] [Can't find port for backend kubernetes service](https://github.com/Kong/kubernetes-ingress-controller/blob/6988320be0b461f09a5213634a8be8bc39b549a6/internal/dataplane/parser/parser.go#L310) (#3138)
    - [x] [HTTPRoute can't be routed](https://github.com/Kong/kubernetes-ingress-controller/blob/9ef0375a643822c6ac3e18e1bda696ee0f6bf9bb/internal/dataplane/parser/translate_httproute.go#L32) (https://github.com/Kong/kubernetes-ingress-controller/pull/3167)
    - [x] [Requested backendRef, but no ReferenceGrant permits it](https://github.com/Kong/kubernetes-ingress-controller/blob/cd73e4b2edbadc652e9eea063c0e4c850f61fd58/internal/dataplane/parser/wrappers_backendref.go#L138) ([handled by the controller](https://github.com/Kong/kubernetes-ingress-controller/blob/04f4d3b882a3f32402c9d3a7887ce2ba50c38e3f/internal/controllers/gateway/httproute_controller.go#L535))
3. [x] Use `[]TranslationFailure` to produce `corev1.Events` (https://github.com/Kong/kubernetes-ingress-controller/pull/3125)
5. [x] Update https://docs.konghq.com/kubernetes-ingress-controller/latest/troubleshooting/ docs. ([#4779](https://github.com/Kong/docs.konghq.com/pull/4779))

### Additional information

PoC: https://github.com/Kong/kubernetes-ingress-controller/pull/3088 

### Acceptance Criteria

- [x] When any _validation error_<sup>1</sup> is detected in the parser, a warning `corev1.Event` is created with the `KongConfigurationTranslationFailed` reason and a detailed human-readable message describing the reason. 
- [x] Every `KongConfigurationTranslationFailed` is associated with all objects that may be affected by the translation error (e.g. faulty CA certificate affecting a KongPlugin)
- [x] Documentation is updated so that users understand they can query Events in order to mitigate problems with their configuration (a new section under https://docs.konghq.com/kubernetes-ingress-controller/latest/troubleshooting/ could be added?)

[1] a validation error is considered to be any code branch in the parsing routines under `internal/dataplane/parser` that ends up with a `continue` statement and an error log.
