### ISSUE TITLE
Assign proper priority of route in translating to expression based routes

### ISSUE THREAD

**Issue by randmonkey** [Kong/kubernetes-ingress-controller#3958]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

part of #3730.

Kong route have a `priority` field to annotate the priority of the route when kong is running expression based router. The field is a 64-bit integer, where larger number means the route has a higher priority.
We need to assign proper priority in the following situations:
- assign different priorities for routes from different types of paths in ingresses
- assign different priorities for routes translated from matches and rules in HTTPRoutes (ref: https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.HTTPRouteRule)
- assign different priorities for routes translated from matches and rules in GRPCRoutes (ref: https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1alpha2.GRPCRouteRule)
- calculate proper priority values from user's annotation to assign priority to objects.

### Proposed Solution

- Implement an algorithm to decide the priority value for each `ingress.spec.rule[*]`
- Implement an algorithm to decide the priority value for each `httproute.spec.rules[*].matches[*]`
- Implement an algorithm to decide the priority value for each `grpcroute.spec.rules[*].matches[*]`
- define the interface to specify priority in annotations every kind of supported resources
- implement a method to override or modify calculated priority value by values from user's specification in annotations

### Acceptance Criteria

- [x] Have proper (different) priority values for different kind of paths in ingresses
- [x] Assigns correct priority values that could pass related conformance tests on mathcing priorities of HTTPRoute and GRPCRoute
- [ ] Has the interface to specify custom priority in annotations
```[tasklist]
### Tasks
- [ ] https://github.com/Kong/kubernetes-ingress-controller/issues/4248
- [ ] https://github.com/Kong/kubernetes-ingress-controller/issues/4249
- [ ] https://github.com/Kong/kubernetes-ingress-controller/issues/4250
```

**Comment by rainest** [comment]
We're good to close this, yes?

**Comment by randmonkey** [comment]
Yes, this could be closed now.
