### ISSUE TITLE
Enforce `KongUpstreamPolicy` status

### ISSUE THREAD

**Issue by mlavacca** [Kong/kubernetes-ingress-controller#5291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

`KongUpstreamPolicy` status must be enforced and kept up-to-date by a proper `KongUpstreamPolicy` controller.

### Additional information

The following is a list of all the issues to complete this task

```[tasklist]
### Tasks
- [ ] https://github.com/Kong/kubernetes-ingress-controller/issues/4932
- [ ] https://github.com/Kong/kubernetes-ingress-controller/issues/5293
- [ ] https://github.com/Kong/kubernetes-ingress-controller/issues/5249
- [ ] https://github.com/Kong/kubernetes-ingress-controller/issues/5292
```
