### ISSUE TITLE
Implement conversion from a Kubernetes store snapshot to a graph

### ISSUE THREAD

**Issue by czeslavo** [Kong/kubernetes-ingress-controller#5929]
Implement a function/stuct converting a Kubernetes store snapshot into its graph representation. The graph should use Kubernetes objects as its vertices and the edges between them should define dependencies (Ingress depending on a Service, Plugin depending on an Ingress/Service/Consumer, etc.). 

The graph will be used to determine what objects need to removed/replaced during the fallback configuration build process - traversing the graph should allow identifying an invalid object's dependants and removing/replacing them along with it.

Blocked by https://github.com/Kong/kubernetes-ingress-controller/issues/5928.
```[tasklist]
### Tasks
- [x] Prepare scaffolding for converting Kubernetes store snapshot to a grpah
- [x] Implement ResolveDependency for Gateway API
- [x] Implement ResolveDependency for Kong CRDs
```

**Comment by czeslavo** [comment]
I've implemented dependency resolving for Gateway API and Ingress types - Kong CRDs are left to be done: https://github.com/Kong/kubernetes-ingress-controller/blob/main/internal/dataplane/fallback/graph_dependencies_kong.go
