### ISSUE TITLE
Documents for using custom entities in KIC

### ISSUE THREAD

**Issue by randmonkey** [Kong/kubernetes-ingress-controller#5992]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this enhancement require public documentation?

- [X] I have added an Acceptance Criteria item for adding and/or adjusting public documentation (if applicable)

### Problem Statement

Split from #4556 custom entities.
We need to add the guide to introduce how to use Kong custom entities in k8s when KIC supports them.

### Proposed Solution

- Add a guide page in KIC docs to introduce how to setup a plugin (like `degraphql`) using custom entities
- Introduce the `KongCustomEntity` CRD in references 

### Acceptance Criteria

- [x] KIC docs includes a guide page for using custom entities  https://github.com/Kong/docs.konghq.com/pull/7486
- [x] KIC docs includes reference of `KongCustomEntity` CRD. https://github.com/Kong/docs.konghq.com/pull/7475 

```[tasklist]
### Tasks
- [ ] https://github.com/Kong/docs.konghq.com/pull/7479
```
