### ISSUE TITLE
Improve observability around config sync

### ISSUE THREAD

**Issue by lahabana** [Kong/kubernetes-ingress-controller#6191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this enhancement require public documentation?

- [X] I have added an Acceptance Criteria item for adding and/or adjusting public documentation (if applicable)

### Problem Statement

There are metrics to see how long sync takes: https://docs.konghq.com/kubernetes-ingress-controller/latest/production/observability/prometheus/#ingress_controller_configuration_push_duration_milliseconds

A user is suggesting adding this to logs.

https://github.com/Kong/kubernetes-ingress-controller/blob/95af584ab560822a40ee6a1dd66a2005f9663e71/internal/dataplane/sendconfig/sendconfig.go#L104

Is this something we want to do?

### Acceptance Criteria

- [ ] Potentially log duration
```[tasklist]
### Tasks
- [ ] #6362
- [ ] https://github.com/Kong/kubernetes-ingress-controller/issues/6363
```

**Comment by mheap** [comment]
The request is a little more involved. They'd like timings for each phase e.g.

* Fetch from k8s API server
* Translate to Kong format
* Sync with Konnect

**Comment by lahabana** [comment]
This looks a lot like tracing to me but tracing without an originator is a little unusual.

**Comment by tao12345666333** [comment]
I have previously attempted to add tracing support for KIC (for performance testing purposes). 

previously proposal here: https://docs.google.com/document/d/1iSWDjODhupV-1GxIBCsDcXbyrAyMghl2zg9wKXMPRVU/edit?usp=sharing

Example 

![img](https://lh7-rt.googleusercontent.com/docsz/AD_4nXdmg5z-1dV91ybprdnI_bPMCQB7pshi2TbylynOlC3jvNh7XzGW34SzCQyS_3PV6unSos4CPIyH2ahYR8tU42g6Wf_6hkgNCNv3_ftbeHjW4BE0y6CPDbu8n4oILs6Jg4kBi-XcWIDMPYcT6GyJ9UUNl5Y?key=v7zv9mrQSUy34uDesGMlbg)
