### ISSUE TITLE
Send configuration to Konnect in a separate loop

### ISSUE THREAD

**Issue by randmonkey** [Kong/kubernetes-ingress-controller#6325]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this enhancement require public documentation?

- [X] I have added an Acceptance Criteria item for adding and/or adjusting public documentation (if applicable)

### Problem Statement

Extension of #6188.
Currently translating Kong configurations, sending configuration to Kong gateways and uploading configuration to Konnect are done in the same sync loop. The sync loop runs every 3 second by default. The frequent update to Konnect could cause two problems:
- Uploading config to Konnect with GDR sync is slow. It requires listing ALL entities by type and uploading the "diffs" one entity each. This will cost too much time in the iteration of sync loop. Although we can resolve the blocking by spawning goroutines to do this in the sync loop (#6188), there would also be potential problems in the spawned goroutines running in the same time.
- Brings pressure to Konnect API servers. running full sync every 3 seconds will bring much load and burst to Konnect's API servers.

### Proposed Solution

- Upload translated configuration to Konnect in a separate loop. The "main" loop translates k8s resources to Kong configuration, send config to gateways and send the `KongState` to the konnect upload loop.
- Add another CLI flag to configure the period of uploading config to Konnect. The default value could be set longer. 

### Acceptance Criteria

- [x] Uploading config to Konnect is done in a separate loop
- [x] Can configure different periods to sync config for the "main" update config loop and Konnect upload loop
```[tasklist]
### Tasks
- [ ] https://github.com/Kong/kubernetes-ingress-controller/issues/6337
- [ ] https://github.com/Kong/kubernetes-ingress-controller/issues/6338
- [ ] https://github.com/Kong/kubernetes-ingress-controller/issues/6339
- [ ] https://github.com/Kong/kubernetes-ingress-controller/issues/6340
```
