### ISSUE TITLE
☔ Support configuring upstream TLS verification

### ISSUE THREAD

**Issue by randmonkey** [Kong/kubernetes-ingress-controller#6374]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this enhancement require public documentation?

- [X] I have added an Acceptance Criteria item for adding and/or adjusting public documentation (if applicable)

### Problem Statement

Extended from FTI-6130.
Customer wanted to configure TLS verification on upstream services by `tls_verify` and `ca_certificates` attributes of Kong service, but we do not have annotations to specify the fields.
Also, gateway API has `BackendTLSPolicyValidation` to specify upstream TLS verification.
We should add the support of specifying TLS verification on KIC by both annotations and gateway APIs.

### Proposed Solution

- Add annotations (on `Service` and `KongServiceFacade`) to specify `tls_verify` and `ca_certificates` in translated Kong service
- Support translating `BackendTLSPolicyValidation` in gateway APIs

```[tasklist]
### Acceptance criteria
- [ ] https://github.com/Kong/kubernetes-ingress-controller/issues/6630
- [ ] https://github.com/Kong/kubernetes-ingress-controller/issues/6631
- [ ] https://github.com/Kong/docs.konghq.com/issues/8133
- [ ] https://github.com/Kong/kubernetes-ingress-controller/issues/6633
```

**Comment by lahabana** [comment]
@randmonkey this almost feels like 2 distinct issues no?

**Comment by czeslavo** [comment]
@lahabana I agree that two issues are creeping in here: one for covering Ingress API with annotations on a `Service` (and possibly a `ServiceFacade`) and another for implementing a `BackendTLSPolicy` for Gateway API. This can remain an umbrella as it makes logical sense to group them under the general TLS verification between a Gateway and upstreams.
