### ISSUE TITLE
☔  Konnect integration improvements

### ISSUE THREAD

**Issue by czeslavo** [Kong/kubernetes-ingress-controller#6388]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this enhancement require public documentation?

- [X] I have added an Acceptance Criteria item for adding and/or adjusting public documentation (if applicable)

### Problem Statement

This issue is an epic issue that gathers all Konnect integration improvements that aim to make the experience of debugging, investigating, and testing it as robust as possible. It is a result of the https://github.com/Kong/kubernetes-ingress-controller/issues/6236 spike.

### Acceptance Criteria

```[tasklist]
### Testing
- [ ] https://github.com/Kong/kubernetes-ingress-controller/issues/3550
```

```[tasklist]
### Observability
- [ ] https://github.com/Kong/kubernetes-ingress-controller/issues/6240
```
