### ISSUE TITLE
☔ Migrate CRDs to kong/kubernetes-configuration repo

### ISSUE THREAD

**Issue by randmonkey** [Kong/kubernetes-ingress-controller#6488]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this enhancement require public documentation?

- [X] I have added an Acceptance Criteria item for adding and/or adjusting public documentation (if applicable)

### Problem Statement

Now we have created kong/kubernetes-configuration repository to store CRDs corresponding to Kong configuration. The repo is expected to be shared by KIC and KGO. We need to import source of CRDs from internal packages to packages in kong/kubernetes-configuration.

### Proposed Solution

- Change import source of CRDs to packages in kong/kubernetes-configuration
- Change the scripts to download CRD manifests from kong/kubernetes-configuration
- Remove CRD packages and CRD manifests in the repo (Should we do this? Maybe there are dependencies elsewhere)

### Acceptance Criteria

- [x] KIC imports CRDs from kong/kubernetes-configuration repo
- [x] KIC generate manifests from CRDs downloaded from  kong/kubernetes-configuration repo
- [x] Documents mentioning CRD download URLs changed to URLs in  kong/kubernetes-configuration

```[tasklist]
### Tasks
- [ ] https://github.com/Kong/kubernetes-ingress-controller/issues/6578
- [ ] https://github.com/Kong/kubernetes-configuration/issues/105
- [ ] https://github.com/Kong/kubernetes-ingress-controller/issues/6618
- [ ] https://github.com/Kong/kubernetes-ingress-controller/issues/6579
- [ ] https://github.com/Kong/kubernetes-ingress-controller/issues/6580
- [ ] https://github.com/Kong/kubernetes-ingress-controller/issues/6581
- [ ] https://github.com/Kong/kubernetes-ingress-controller/issues/6641
- [ ] https://github.com/Kong/kubernetes-ingress-controller/issues/6663
- [ ] https://github.com/Kong/kubernetes-ingress-controller/issues/6635
```

**Comment by randmonkey** [comment]
It is required for KGO to operate it.

**Comment by czeslavo** [comment]
We should also take care of handling the control plane reference in KIC and ignore objects that are not attached to other CPs (have the reference non-empty and refer to non-KIC CP).

**Comment by programmer04** [comment]
Every task has been resolved 🎉
