### ISSUE TITLE
:umbrella:  Custom Entity GA

### ISSUE THREAD

**Issue by randmonkey** [Kong/kubernetes-ingress-controller#6553]
We want to make usage of Kong custom entities GA in KIC 3.4. 
```[tasklist]
### Tasks
- [ ] https://github.com/Kong/kubernetes-ingress-controller/issues/6628
- [ ] https://github.com/Kong/kubernetes-ingress-controller/issues/6629
- [ ] https://github.com/Kong/kubernetes-ingress-controller/issues/6794
```

**Comment by lahabana** [comment]
Things to do:

- Review docs, make sure we have a guide for it.
- Ask @mheap about feedback from users so we know if there’s any improvement needed (docs or issues encountered).

**Comment by pmalek** [comment]
When #6802 gets reviewed and merger we can close this one.


All other tasks related to custom entity feature validation from #6629 have been done.

**Comment by pmalek** [comment]
This is now done.
