### ISSUE TITLE
Firm up release instructions and create template checklist

### ISSUE THREAD

**Issue by rainest** [Kong/kubernetes-ingress-controller#890]
For 0.10.0, we documented the KIC release process. During the 1.0.0-rc.1, I found some areas for improvement, and noted some steps that probably do not apply during RC releases. #887 and #889 notes and comments in the current internal document cover those.

One of the main things I noticed is that we currently just have a bulleted list, and would probably benefit from a checklist to keep track of steps performed in a given release.

Google Docs (the process doc's current home) does provide support for both templates and checklists, but I have some misgivings with it:
- Organization: Google Drive is, at least for me, a magical tool for losing documents unless you're lucky enough to have linked them from elsewhere
- Poor suitability for writing that's heavy with technical text examples: STOP AUTOCORRECTING ME GOOGLE DOCS I DON'T WANT A CAPITAL LETTER THERE AND I SURE AS HELL DON'T WANT CURLY QUOTES. THIS ISN'T A PRETTY PRINT DOCUMENT)
- Annoying clipboard interference: at least for me, a hurdle is that it breaks Linux Xorg-buffer stuff--I don't use a clipboard manager (because I'm a luddite) and need to copy commands into a notepad app before I can paste them into a terminal. That's kinda good because it forces me to edit before pasting and possibly accidentally running something, but still annoying. 

Other options are Confluence (which we use for the Enterprise release checklist) and a custom Github issue type:

https://support.google.com/a/users/answer/9308885?hl=en
https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/configuring-issue-templates-for-your-repository
https://confluence.atlassian.com/doc/create-a-template-296093779.html

Github issue seems a pretty decent candidate as we're moving a bunch of other stuff there, and I don't think there's anything sensitive in the process instructions. Minor problem might be that there's no way to restrict an issue type to maintainers, but we can hopefully rely on the good will of the community to not create release issues (and can stick a reminder at the top if we think it necessary), and worst case would just need to delete any that aren't ours. It at least appears to support nested checklists with indented code block examples, although the advanced checklist features may not be well-documented (or documented at all--it may well be an unintended quirk of GHFMD). I don't think there's any way to automatically get the indentation correct, but setting that up is pretty much a one-time annoyance. For example, some comically abbreviated steps:

- [x] Merge main into next
- [ ] Docker build and push
  - [ ] Build the container
  ```
  make container
  ```
  - [ ] Push the container
    - [ ] Push version tag
    ```
     docker push kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller:0.10.0
    ```
    - [x] Push latest tag
    ```
     docker push kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller:latest
    ```

Confluence allows for much richer formatting and hybrid WYSIWYG+Markdown (sometimes? Confluence can be weird about doc types not supporting Markdown yet, dunno why--one-off either way), but suffers from being slow. However, its slowness mainly affects editing, and for most uses of the template we'll just be spawning a new doc based on it, and once we have the templated doc, ticking boxes and copying examples, so Atlassian slowness is less of a concern than it is normal.

**Comment by rainest** [comment]
Extra notes:
- Looks like the team-k8s automation sends things directly to To Do if you submit to the board from an issue. Do we want groomed backlog instead?
- I cannot actually create custom issue types for this repo, or see its Settings tab at all. I think that was a permissions thing we intended to fix, but didn't.

**Comment by shaneutt** [comment]
Talked with @rainest we're going to close this one for now as there's not a significant impetus to make changes at this point in time.
